# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # ORG_NAME
  # ---------------------------------------------------------------------------
  - Name: ORG_NAME_LOWERCASE
    Domain: ORG_NAME_LOWERCASE.kingland.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
