NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org6.kingland.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org6.kingland.com-cert.pem
    OrganizationalUnitIdentifier: peer
