#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  couchdb8:
    container_name: couchdb8
    image: hyperledger/fabric-couchdb:latest
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "12984:5984"

  peer0.org8.kingland.com:
    container_name: peer0.org8.kingland.com
    extends:
      file:  base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org8.kingland.com
      - CORE_PEER_LOCALMSPID=Org8MSP
      - CORE_PEER_ADDRESS=peer0.org8.kingland.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb8:5984
    ports:
      - 14051:7051
      - 14053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org8.kingland.com/peers/peer0.org8.kingland.com/:/etc/hyperledger/crypto/peer
        - ../mount/peer0.org8.kingland.com/var/hyperledger/production:/var/hyperledger/production
    depends_on:
        - couchdb8
    extra_hosts:
        - "orderer1.kingland.com:172.16.10.18"
        - "orderer2.kingland.com:172.16.10.18"
