#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb:latest
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "9984:5984"

  peer1.org1.kingland.com:
    container_name: peer1.org1.kingland.com
    extends:
      file:  base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.kingland.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.kingland.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
    ports:
      - 11051:7051
      - 11053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/org1.kingland.com/peers/peer1.org1.kingland.com/:/etc/hyperledger/crypto/peer
        - ../mount/peer1.org1.kingland.com/var/hyperledger/production:/var/hyperledger/production
    depends_on:
        - couchdb5
    extra_hosts:
        - "orderer1.kingland.com:172.16.10.18"
        - "orderer2.kingland.com:172.16.10.18"
